### ISSUE TITLE
IndexError: list index out of range error in vertical hist

### ISSUE THREAD

**Issue by tyiannak** [nschloe/termplotlib#44]
Amazing lib thanx alot @nschloe !

I am facing the following error (I am also pasting the arrays i am using for histogram and bins that might help you i guess):

```
Traceback (most recent call last):
  File "paura_lite.py", line 30, in <module>
    fig.hist(X2, freqs2, grid=[25, 25], force_ascii=False)
  File "/usr/local/lib/python3.6/site-packages/termplotlib/figure.py", line 56, in hist
    self._content.append(hist(*args, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/termplotlib/hist.py", line 22, in hist
    force_ascii=force_ascii,
  File "/usr/local/lib/python3.6/site-packages/termplotlib/hist.py", line 123, in hist_vertical
    if row[pos] == 8 and (pos + 1 == len(row) or row[pos + 1] > 0):
IndexError: list index out of range
```

X2 and freqs2 are respectively (plotting the same arrays with either plot or horizontal histogram works just fine fyi 
```
[124.41883839  35.41717879  31.53559882  28.65272995  21.51772978
  18.91799348  17.13384018  16.4547271   15.12907567  12.27610031
  12.89634676  10.55464499  10.1385237    9.76782805   8.12663877
   7.21406045   5.71375229   4.28627088   3.3031431    2.84735662]
[   0.  200.  400.  600.  800. 1000. 1200. 1400. 1600. 1800. 2000. 2200.
 2400. 2600. 2800. 3000. 3200. 3400. 3600. 3800. 4000.]

```

**Comment by nschloe** [comment]
I need an mwe to reproduce.

**Comment by tyiannak** [comment]
pasting the exact same arrays for which it fails: 
`import termplotlib as tpl
import numpy
x = numpy.array([124.41883839,35.41717879,31.53559882,28.65272995,21.51772978,18.91799348,17.13384018,16.4547271, 15.12907567,12.27610031,12.89634676,10.55464499,10.1385237,9.76782805, 8.12663877,7.21406045, 5.71375229, 4.28627088, 3.3031431,2.84735662])
y = numpy.array([0.,200.,400.,600.,800.,1000.,1200.,1400.,1600.,1800.,2000.,2200.
,2400.,2600.,2800.,3000.,3200.,3400.,3600.,3800.,4000.])
fig = tpl.figure()
fig.hist(x, y, grid=[100, 105], force_ascii=False); fig.show()`

**Comment by nschloe** [comment]
Remove
```python
grid=[100, 105]
```
![k](https://user-images.githubusercontent.com/181628/83405389-b2875d80-a40c-11ea-80b7-d1ff6735f5ff.png)
