### ISSUE TITLE
horizontal lines 

### ISSUE THREAD

**Issue by krober10nd** [nschloe/termplotlib#49]
The following code: 

``` 
import termplotlib as tpl
import numpy
 
numpy.random.seed(123)
sample = numpy.random.normal(size=1000)
counts, bin_edges = numpy.histogram(sample, bins=40)
fig = tpl.figure()
fig.hist(counts, bin_edges, grid=[15, 25], force_ascii=False, bins=60)
fig.show()
```

produces this with horizontal lines crossing:

<img width="301" alt="Screen Shot 2020-10-01 at 9 17 34 PM" src="https://user-images.githubusercontent.com/18619644/94875623-aa2b4780-042b-11eb-999a-f91d6a0f4ad5.png">

I'm on Mac OS Catalina 10.15 using the standard bash shell with UTF-8 encoding, with SF Mono Regular 11 pt font (which I believe is the default).

**Comment by krober10nd** [comment]
opa. well turned out my linspacing needed to below 1 (linpspacing = 0.805)
<img width="1440" alt="Screen Shot 2020-10-01 at 9 23 05 PM" src="https://user-images.githubusercontent.com/18619644/94875887-6f75df00-042c-11eb-8c9a-c16ff918cf63.png">

**Comment by nschloe** [comment]
Good catch.
