### ISSUE TITLE
Printing to file

### ISSUE THREAD

**Issue by jaimejim** [nschloe/termplotlib#50]
More of a question really.  If I open a file in "w" mode, what's the right way to dump the drawing into a file? I am trying various combinations of file.write() and also "wb" mode but with no success. Another option I am thinking is something like os.system('python plot-mything.py') but it is very ugly.

**Comment by jaimejim** [comment]
Nevermind, immediately after I tried:

sys.stdout = open("out.md", "w")
print(fig.show())

That works.

**Comment by nschloe** [comment]
Instead of `show()`, you can use `get_string()`; this is probably cleaner.
